helmOperator:
  create: false
#
# @CHANGEME - Update url to your public repo URL
#
git:
  url: "git@github.com:onedr0p/homelab-gitops.git"
  branch: master
  path: deployments
image:
  repository: raspbernetes/flux
  tag: 1.20.2
registry:
  rps: 1
  burst: 1
memcached:
  enabled: true
syncGarbageCollection:
  enabled: true
  dry: false
# # Enabled once prometheus-operator is installed
# prometheus:
#   enabled: true
#   serviceMonitor:
#     create: false
#     interval: 30s
#     scrapeTimeout: 10s
#     namespace: flux
