---

- name: Set the current MAC address for eth0.
  set_fact:
    _mac_address: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"

- name: Set variables based on eth0 MAC address.
  set_fact:
    _hostname: "{{ mac_address_mapping[_mac_address].name }}"
    _ip_address: "{{ mac_address_mapping[_mac_address].ip }}"

- name: Update hostname
  template:
    src: "templates/hostname.j2"
    dest: "/etc/hostname"
    mode: 0644

- name: Run hostname command
  command: "hostname {{ _hostname }}"

- name: Update dhcpcd.conf
  template:
    src: "templates/dhcpcd.conf.j2"
    dest: "/etc/dhcpcd.conf"
    mode: 0644

- name: Update hosts
  template:
    src: "templates/hosts.j2"
    dest: "/etc/hosts"
    mode: 0644
