---

- name: Install packages to build userland
  apt:
    name:
      - pkg-config
      - build-essential
      - cmake
    install_recommends: false
    update_cache: true
    # Need the force_apt_get until
    # https://github.com/ansible/ansible/issues/56832
    force_apt_get: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success

- name: Clone userland
  git:
    repo: "https://github.com/raspberrypi/userland.git"
    dest: /tmp/userland
    version: 42ec119e03eb8dffc7c83e2ac0e665e333abbef6

- name: Copy aarch64.patch
  copy:
    src: aarch64.patch
    dest: /tmp/userland/aarch64.patch

- name: Apply aarch64.patch
  command: git apply aarch64.patch
  args:
    chdir: "/tmp/userland"

- name: Build userland
  command: ./buildme --aarch64
  args:
    chdir: "/tmp/userland"

- name: Setup shared library paths
  shell: echo /opt/vc/lib | tee /etc/ld.so.conf.d/00-vmcs.conf

- name: Exec ldconfig
  command: ldconfig

- name: Allow users to run userland commands without sudo
  blockinfile:
    path: /etc/udev/rules.d/99-custom-permissions.rules
    marker: "# {mark} ANSIBLE ALLOW USERLAND"
    create: yes
    block: |
      SUBSYSTEM=="vchiq",GROUP="users",MODE="0660"
      SUBSYSTEM=="vcio",GROUP="users",MODE="0660"
      SUBSYSTEM=="argon-h264mem",GROUP="users",MODE="0660"
      SUBSYSTEM=="argon-hevcmem",GROUP="users",MODE="0660"
      SUBSYSTEM=="argon-intcmem",GROUP="users",MODE="0660"
      SUBSYSTEM=="argon-vp9mem",GROUP="users",MODE="0660"
      SUBSYSTEM=="rpivid-h264mem",GROUP="users",MODE="0660"
      SUBSYSTEM=="rpivid-hevcmem",GROUP="users",MODE="0660"
      SUBSYSTEM=="rpivid-intcmem",GROUP="users",MODE="0660"
      SUBSYSTEM=="rpivid-vp9mem",GROUP="users",MODE="0660"

- name: Remove packages that were require to build userland
  apt:
    name:
      - pkg-config
      - build-essential
      - cmake
    state: absent

- name: Clean up apt
  apt:
    autoremove: true
    # Need the force_apt_get until
    # https://github.com/ansible/ansible/issues/56832
    force_apt_get: true
