apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAFb8AvyuwE3R8X8B7DlwQdzrhkAyPN/1NlPIGaileqJYqBez/Hp/htkRlGxR+OFNayMvQshNuX+2kD9a4YHrl3/eAqG4UZJxLyZONos8kGD5uA1xDcjmh5XjGK6geOBwStIlf+9lM6onHRZzgookwNW/HwFpkelrl3tjqs5iD24cSzcPHH9Lo5R3haiLJvrsJXwB/63v+UChDxLXFoyeJzFq9Zu+z87KNzkBSuNbGLHfBlwO7BX90uliDpCb4XrasC9atd1EPiQwTANveWFiOIJoiVNzl0Mrqj4xdKE83eooBjItZQo5OIwrrA+TzcZ3lZHC8qHtggrLwSeTnr9I0hWufqWPLU0/cTYOcWFwH+RvgLcr+dYR7d0F+IPa0v1OgOwGrGeHHRPMeH8TXhGbs2fk7Yjiy8/2OZ0izaSGCirCiH4CxYN1eO6f3CAEmpS4mBDVw4TmY5LOJODCf8bYp9ZCrCiE3x5zHsWyjhhH28XbX9Lpk3zB7jVkldgIUjxBJjEidI2PCbjIJtAa7hJOamHwKBSxiz1IX4+82TUQDvu6Df6Rz4eR1W38DcSVYnopbQEpne8hxumw+rIle4tB0V6PMPy6m4ysRy3uTFfrzLLwwNPUIBS3YR9/Jtr8XryvAaskXHejgXyh0d5fX5Cx+uJat+8xBKvWdlgAo/DO2PVSk2Ff/QZ5Z8EnDMJ68eu5J0IAv8a5+psrJ2NKUgZ2bB52xKLnHXhy0vuzvc1lRhR8B0h6QJILQZpE0mS5LsyREfvoJQNo7vtFzDgbpPb7VGo/3wLw/bGN5/rCLPwbSTeJr3QXEEilWL5BfyzPia/k18bkHXR6fiSBE1Tuhl1VDhhDWLjTVkHpYV22vb5mAuEeA8/fL91bbGDIZwmFB2BEnu6QjXmbKfcM54AC6Yia4n/u4zMcuCj2fMQ0EhT9IGR6S5Iuu3Ek2hyF+rAtQyR1NaanTCB+LPO2VIae4fdnCi2tK2dyIZkUSLawrGtff8E3Mhg0PHGKg=
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default
status: {}

