apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbget-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgB7J76ddbsMDghIL5+SRVgMe6Q9X0GixWyXSIBih4TeVZ1T8FASzuNwG15SpajpbezuIqB+Isv9f7RHjHllT2D5+CL3lecVFQ6ayVwJw1+a3ib5TDWoqQF3Bz48niMDXSUWSlZYLLDJ455Viw10MTo1nZ/KE6fDFF+7WRUkkFdpTGXUO5zSD7FunbKU1APDo8u0695ZmFNX4JUYhA01Hdt954bZmR4k0ityaicnP5nR4lAnqBMezzYSF8YRw3mQ+nViU+STk98fN8JKMtAz2PAuKPNwYl4zfj/elQ8ylcYI/QcJ/yfAA1WsHDlCJVHxhbvBYoQ+ylu8rRcmO3IWn5X7dcjTMewrIGaxMJ1njaPTMzVfWC+iwXsJj06goiPsQQjmrQG1oZCaRHMcfUY13G2+QT808cImlCz8PgpDAWPyU4UrnRRdOPiJPm+8rYdXCxQThfXzx9BSl0Nux8Wt43edxVbBUFomwNL1WH7GdDnpbiM2VYRMhmYQHMF3sT+RSpfVYthIGkihR1ex9cWMG4SpeFNLkkmBAxhFl7BKG4bMiJc0p4ZFZz2ULJ34NtP5temDyB252iZkHOAaWgHA1f0flKL+pgBb4nl9RwHs2X8eP0b+GPOwMIiFElWdQn73X5QpyjX8rroH22cHJU/GTFRtUIRDBNg9RzQALI18UmcAvqnjkoq9vT95xXwMnQURRmujyiqE92bj+k0fsWMQrnnrZ35WEyBpsaQ5S6woybKrsBoT1ALOL2+dvWfmXWf+vnpMdJG73yavhTOMa5CKMUJub+6Ir9VBTTj7qBQytdjSlOdYWZ5vZEAsrqccAdM/D4qWn3LqTlDUF32p4txzUXRYKloB70fMZcm1Q/r+JNFjoJYrFhnwqAQiHARmt2P5EtBSkeNPYNCqgsxh37xUJ6nHySKAfU38rlcNe/gDxFNcBO+lBsDgFzNscr6EbQsFmBuoug9v7yrsVyGy6Utqf6qhPwb648Plrqf9V2+HfDUnkl81PpF9Bqs=
  template:
    metadata:
      creationTimestamp: null
      name: nzbget-helm-values
      namespace: default
status: {}

