apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBVKWSCuvCAwGTzqq7HRWuX1T0x1lEKiTzoY2YtCH5C0V4H5XYMWJzOC1dyuHw0t8fUBcQhdLqkB2EHp26BlbxCWfCOiWWn/ZVls1RdNqIeH+85qM1IHZjCRzjuXI5o/GHcrEoF2/olAeBhXcr7uMzhIjLNJ6IWQdml2PcgWb5Ak3v2p5NO/x2SVx1lOewtwzgRv72YVPCx8HsVUAHzounpT3g0ZNjtZC5KrJvyhXetPj6GmCwhE5Z39uulDPluEX3Xsye8CTpNe/pa6ZFCl+Gnm031lJ3dFaazYlynt5jjxsf1/cuiFtwOiX2xJv2VQpLYKN24Qixy+gR8l61HGfm7ct0c3WxkfmEtO7a61UNb41PVA/mX7+F05crNAWdec2aEB96YpCQvYlnKk4FQczHyLewxRFXGLTmcsxOpIM52Aq/OYbWJged2PW9Wb8qS7+acQ4/1D28i0Z2/2Krac/dgivU+45+bBTVlJB58c0t3mHIVyFMZr0FBLbuqAz1gis//EFyICV899FZNz3Uv4kiqTBc1zh8tb5RG1Kzrse9oo5ezZS8Gyx5tnv2fS3u83ARPfHaqyAZRa0ggWNKOtkr7cH/iuLJDXg7WhSiChtv8BwpiW6yA8sblxH5JQqKe8O39eCo/32awBZ8w5sdXZ1JDaJbZAZ4qRpPPQooEe9J/3VObM1O13B+SuKz0O13yfhsSFc0nVWiyXSQ8o+kPmZyGAoufiiiiHuwsuv2pBI1TQ3kRpcGkJpIIfu8ojAZ111DXMULiGnQhPJ4/feWk/eXWKnd1ZjobtG0Zr/PHWAB/oDR0l4BcdxZURIS4YsEuHPCTNwhrW3Fa6Un626fiBXHMJDDkle+DwwEtohVorgg2hZZv/QZshtt4dEtZ6FNTObskA6qvJaYUy7ZXrtpu7Tyre0MtMDNGWUn5fiohTI6mwcBfj7ieHZxtBUTiLDkiVtIBtGUSJK+Ts0merhgoIhhbZviKT5rQd6FcE0Y68tv2crZmYNrceVs=
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default
status: {}

