createCRD: true
git:
  ssh:
    secretName: flux-git-deploy
helm:
  versions: "v3"
image:
  repository: raspbernetes/helm-operator
  tag: v1.0.0-rc9
prometheus:
  enabled: true
  serviceMonitor:
    create: false
    namespace: flux
    interval: 30s
    scrapeTimeout: 10s
